// ©2004-2026 Deep Focus Review. All rights reserved.
export const DEFINITIVES_INTRO = `The Definitives is an ongoing series of long-form critical essays on the films that have most shaped cinema as an art form. Each entry blends critical analysis with an exploration of film history, formal technique, interpretation, and pure appreciation. New essays debut on Patreon before appearing publicly roughly one year later. — Brian Eggert`;

export const DEFINITIVES_FILMS = [
  {
    id: 1,
    title: "The Philadelphia Story",
    year: 1940,
    director: "George Cukor",
    date: "May 26, 2026",
    excerpt: "George Cukor's dizzyingly witty comedy of remarriage remains one of Hollywood's supreme examples of the screwball form — and a film about the costs of perfectionism.",
    image: "https://images.unsplash.com/photo-1562329265-95a6d7a83440?w=600&h=400&fit=crop&auto=format",
    decade: "1940s",
  },
  {
    id: 2,
    title: "Red Sorghum",
    year: 1988,
    director: "Zhang Yimou",
    date: "April 21, 2026",
    excerpt: "Zhang Yimou's debut feature is a sensory assault of red earth and ritual — a film about desire, violence, and survival rendered in images of startling visual force.",
    image: "https://images.unsplash.com/photo-1615414047026-802692414b79?w=600&h=400&fit=crop&auto=format",
    decade: "1980s",
  },
  {
    id: 3,
    title: "Stalker",
    year: 1979,
    director: "Andrei Tarkovsky",
    date: "March 31, 2026",
    excerpt: "Tarkovsky's great film of spiritual yearning moves with the pace of a dream through a forbidden zone — a meditation on faith, hope, and the unknowable.",
    image: "https://images.unsplash.com/photo-1615414015111-8d98cb65677e?w=600&h=400&fit=crop&auto=format",
    decade: "1970s",
  },
  {
    id: 4,
    title: "Sunshine",
    year: 2007,
    director: "Danny Boyle",
    date: "March 22, 2026",
    excerpt: "Danny Boyle's overlooked sci-fi masterwork charts a crew's mission to reignite a dying sun — and finds in that premise an almost unbearable meditation on sacrifice and hubris.",
    image: "https://images.unsplash.com/photo-1631805249874-3f546d176de4?w=600&h=400&fit=crop&auto=format",
    decade: "2000s",
  },
  {
    id: 5,
    title: "M",
    year: 1931,
    director: "Fritz Lang",
    date: "March 10, 2026",
    excerpt: "Fritz Lang's first sound film remains among the most morally and formally complex crime pictures ever made — a city-wide manhunt that implicates everyone, including the audience.",
    image: "https://images.unsplash.com/photo-1568876694728-451bbf694b83?w=600&h=400&fit=crop&auto=format",
    decade: "1930s",
  },
  {
    id: 6,
    title: "Magnolia",
    year: 1999,
    director: "Paul Thomas Anderson",
    date: "February 24, 2026",
    excerpt: "Paul Thomas Anderson's three-hour mosaic of Los Angeles loneliness and coincidence remains one of American cinema's most fearlessly emotional works.",
    image: "https://images.unsplash.com/photo-1715322608224-a9efaeeffaf7?w=600&h=400&fit=crop&auto=format",
    decade: "1990s",
  },
  {
    id: 7,
    title: "Bad Day at Black Rock",
    year: 1955,
    director: "John Sturges",
    date: "February 11, 2026",
    excerpt: "A one-armed stranger arrives in a desert town. John Sturges's CinemaScope western is a taut, allegorical thriller about guilt, complicity, and the silence of bystanders.",
    image: "https://images.unsplash.com/photo-1589569334232-fdc917c38226?w=600&h=400&fit=crop&auto=format",
    decade: "1950s",
  },
  {
    id: 8,
    title: "All About My Mother",
    year: 1999,
    director: "Pedro Almodóvar",
    date: "February 3, 2026",
    excerpt: "Almodóvar's most emotionally generous film follows a grieving mother into a world of performance, solidarity, and transformation — a masterwork of compassionate filmmaking.",
    image: "https://images.unsplash.com/photo-1677536849474-2819061389ed?w=600&h=400&fit=crop&auto=format",
    decade: "1990s",
  },
  {
    id: 9,
    title: "Brute Force",
    year: 1947,
    director: "Jules Dassin",
    date: "January 25, 2026",
    excerpt: "Jules Dassin's ferocious prison noir — suppressed by the censors for its violence and politics — is one of Hollywood's most radical and uncompromising films.",
    image: "https://images.unsplash.com/photo-1575653294195-2f1b52f4d990?w=600&h=400&fit=crop&auto=format",
    decade: "1940s",
  },
];

export const LATEST_REVIEWS = [
  { title: "In the Hand of Dante", year: 2026, rating: "★★" },
  { title: "The Death of Robin Hood", year: 2026, rating: "★★★½" },
  { title: "Toy Story 5", year: 2026, rating: "★★★½" },
];
