// ©2004-2026 Deep Focus Review. All rights reserved.
export interface FilmEntry {
  title: string;
  year: number;
  definitive?: boolean;
}

export const REVIEWS_BY_LETTER: Record<string, FilmEntry[]> = {
  "#": [
    { title: "2001: A Space Odyssey", year: 1968, definitive: true },
    { title: "2046", year: 2004 },
    { title: "8½", year: 1963, definitive: true },
    { title: "10 Cloverfield Lane", year: 2016 },
    { title: "12 Angry Men", year: 1957, definitive: true },
    { title: "12 Years a Slave", year: 2013 },
    { title: "12 Strong", year: 2018 },
    { title: "13 Going on 30", year: 2004 },
    { title: "14 Peaks: Nothing Is Impossible", year: 2021 },
    { title: "20th Century Women", year: 2016 },
    { title: "21 Bridges", year: 2019 },
    { title: "28 Days Later", year: 2002 },
    { title: "28 Weeks Later", year: 2007 },
    { title: "31", year: 2016 },
    { title: "45 Years", year: 2015 },
    { title: "47 Meters Down", year: 2017 },
    { title: "71", year: 2014 },
    { title: "127 Hours", year: 2010 },
    { title: "300", year: 2007 },
    { title: "1408", year: 2007 },
    { title: "1917", year: 2019 },
  ],
  A: [
    { title: "Abduction", year: 2011 },
    { title: "Abigail", year: 2024 },
    { title: "About Elly", year: 2009 },
    { title: "About Time", year: 2013 },
    { title: "Abraham Lincoln: Vampire Hunter", year: 2012 },
    { title: "Absolutely Anything", year: 2017 },
    { title: "The Abyss", year: 1989 },
    { title: "Accidental Love", year: 2015 },
    { title: "The Accountant", year: 2016 },
    { title: "The Accountant 2", year: 2025 },
    { title: "The Accused", year: 1988 },
    { title: "Ace in the Hole", year: 1951, definitive: true },
    { title: "Ad Astra", year: 2019 },
    { title: "Adam", year: 2009 },
    { title: "Adaptation.", year: 2002 },
    { title: "The Adjustment Bureau", year: 2011 },
    { title: "Adventureland", year: 2009 },
    { title: "The Adventures of Baron Munchausen", year: 1988 },
    { title: "The Adventures of Robin Hood", year: 1938 },
    { title: "The Adventures of Tintin", year: 2011 },
    { title: "Afire", year: 2023 },
    { title: "AfrAId", year: 2024 },
    { title: "After Earth", year: 2013 },
    { title: "After Hours", year: 1985 },
    { title: "After the Hunt", year: 2025 },
    { title: "After the Thin Man", year: 1936 },
    { title: "After Yang", year: 2022 },
    { title: "After.Life", year: 2010 },
    { title: "Aftermath", year: 2017 },
    { title: "Aftersun", year: 2022 },
    { title: "The Age of Innocence", year: 1993, definitive: true },
    { title: "Agora", year: 2010 },
    { title: "Aguirre, the Wrath of God", year: 1972, definitive: true },
    { title: "A.I. Artificial Intelligence", year: 2001 },
    { title: "Air", year: 2023 },
    { title: "Akira", year: 1988 },
    { title: "Akira Kurosawa's Dreams", year: 1990 },
    { title: "Aladdin", year: 2019 },
    { title: "Alex Cross", year: 2012 },
    { title: "Alice in Wonderland", year: 2010 },
    { title: "Alice Through the Looking Glass", year: 2016 },
    { title: "Alien", year: 1979, definitive: true },
    { title: "Alien 3", year: 1992 },
    { title: "Alien vs. Predator", year: 2004 },
    { title: "Alien vs. Predator: Requiem", year: 2007 },
    { title: "Alien: Covenant", year: 2017 },
    { title: "Alien: Resurrection", year: 1997 },
    { title: "Alien: Romulus", year: 2024 },
    { title: "Aliens", year: 1986 },
    { title: "Alita: Battle Angel", year: 2019 },
    { title: "All About My Mother", year: 1999, definitive: true },
    { title: "All Dirt Roads Taste of Salt", year: 2023 },
    { title: "All Good Things", year: 2010 },
    { title: "All Is Lost", year: 2013 },
    { title: "All of Us Strangers", year: 2023 },
    { title: "All Quiet on the Western Front", year: 2022 },
    { title: "All That Breathes", year: 2022 },
    { title: "All the Creatures Were Stirring", year: 2018 },
    { title: "All the Money in the World", year: 2017 },
    { title: "All We Imagine as Light", year: 2024 },
    { title: "Allied", year: 2016 },
    { title: "Aloha", year: 2015 },
    { title: "Alpha", year: 2018 },
    { title: "Alpha", year: 2026 },
    { title: "Amadeus", year: 1984, definitive: true },
    { title: "The Amateur", year: 2025 },
    { title: "The Amazing Spider-Man", year: 2012 },
    { title: "The Amazing Spider-Man 2", year: 2014 },
    { title: "The American", year: 2010 },
    { title: "American Factory", year: 2019 },
    { title: "American Fiction", year: 2023 },
    { title: "American Honey", year: 2016 },
    { title: "American Hustle", year: 2013 },
    { title: "American Made", year: 2017 },
    { title: "American Sniper", year: 2014 },
    { title: "American Ultra", year: 2015 },
    { title: "Ammonite", year: 2020 },
    { title: "Amour", year: 2012 },
    { title: "Amsterdam", year: 2022 },
    { title: "An Education", year: 2009 },
    { title: "Anatomy of a Fall", year: 2023 },
    { title: "André Is an Idiot", year: 2026 },
    { title: "Anemone", year: 2025 },
    { title: "Angels & Demons", year: 2009 },
    { title: "Aniara", year: 2018 },
    { title: "Animal Farm", year: 2026 },
    { title: "The Animal Kingdom", year: 2023 },
    { title: "Anna", year: 2019 },
    { title: "Anna and the Apocalypse", year: 2018 },
    { title: "Anna Karenina", year: 2012 },
    { title: "Annabelle", year: 2014 },
    { title: "Annabelle Comes Home", year: 2019 },
    { title: "Annabelle: Creation", year: 2017 },
    { title: "Annette", year: 2021 },
    { title: "Annie Hall", year: 1977, definitive: true },
    { title: "Annihilation", year: 2018 },
    { title: "Anomalisa", year: 2015 },
    { title: "Anon", year: 2018 },
    { title: "Anonymous", year: 2011 },
    { title: "Anora", year: 2024 },
    { title: "Another Earth", year: 2011 },
    { title: "Another Round", year: 2020 },
    { title: "Another Thin Man", year: 1939 },
    { title: "Antebellum", year: 2020 },
    { title: "Antichrist", year: 2009 },
    { title: "Ant-Man", year: 2015 },
    { title: "Ant-Man and the Wasp", year: 2018 },
    { title: "Ant-Man and the Wasp: Quantumania", year: 2023 },
    { title: "Apartment 7A", year: 2024 },
    { title: "Apex", year: 2026 },
    { title: "Apollo 10½: A Space Age Childhood", year: 2022 },
    { title: "Apollo 11", year: 2019 },
    { title: "Apollo 18", year: 2011 },
    { title: "Appaloosa", year: 2008 },
    { title: "The Apprentice", year: 2024 },
    { title: "Aquaman", year: 2018 },
    { title: "Arbitrage", year: 2012 },
    { title: "Are You There God? It's Me, Margaret.", year: 2023 },
    { title: "Area 51", year: 2015 },
    { title: "Argo", year: 2012 },
    { title: "Argylle", year: 2024 },
    { title: "Armageddon Time", year: 2022 },
    { title: "Armand", year: 2025 },
    { title: "Armored", year: 2009 },
    { title: "Army of Darkness", year: 1993 },
    { title: "Army of Shadows", year: 1969, definitive: true },
    { title: "Army of the Dead", year: 2021 },
    { title: "Arrival", year: 2016 },
    { title: "Arsenic and Old Lace", year: 1944 },
    { title: "The Art of Self-Defense", year: 2019 },
    { title: "Art of the Steal", year: 2010 },
    { title: "Art of the Steal", year: 2014 },
    { title: "Artemis Fowl", year: 2020 },
    { title: "Arthur", year: 1981 },
    { title: "Arthur", year: 2011 },
    { title: "Arthur Christmas", year: 2011 },
    { title: "The Artist", year: 2011 },
    { title: "Ash Is Purest White", year: 2018 },
    { title: "Assassin's Creed", year: 2016 },
    { title: "Assassination Nation", year: 2018 },
    { title: "The Assistant", year: 2020 },
    { title: "Asteroid City", year: 2023 },
    { title: "The A-Team", year: 2010 },
    { title: "Atomic Blonde", year: 2017 },
    { title: "Attack the Block", year: 2011 },
    { title: "Audition", year: 1999 },
    { title: "August: Osage County", year: 2013 },
    { title: "Australia", year: 2008 },
    { title: "The Autopsy of Jane Doe", year: 2016 },
    { title: "Avatar", year: 2009 },
    { title: "Avatar: Fire and Ash", year: 2025 },
    { title: "Avatar: The Way of Water", year: 2022 },
    { title: "The Avengers", year: 2012 },
    { title: "Avengers: Age of Ultron", year: 2015 },
    { title: "Avengers: Endgame", year: 2019 },
    { title: "Avengers: Infinity War", year: 2018 },
    { title: "Away From Her", year: 2007 },
    { title: "Away We Go", year: 2009 },
    { title: "Azrael", year: 2024 },
  ],
  B: [
    { title: "The Babadook", year: 2014 },
    { title: "Baby Driver", year: 2017 },
    { title: "Babylon", year: 2022 },
    { title: "Bad Boys for Life", year: 2020 },
    { title: "Bad Day at Black Rock", year: 1955, definitive: true },
    { title: "Bad Education", year: 2019 },
    { title: "Bad Times at the El Royale", year: 2018 },
    { title: "Bamboozled", year: 2000, definitive: true },
    { title: "Barry Lyndon", year: 1975, definitive: true },
    { title: "Barton Fink", year: 1991, definitive: true },
    { title: "The Batman", year: 2022 },
    { title: "Batman Begins", year: 2005 },
    { title: "Batman v Superman", year: 2016 },
    { title: "Battle of Algiers", year: 1966, definitive: true },
    { title: "Beau Is Afraid", year: 2023 },
    { title: "Being John Malkovich", year: 1999 },
    { title: "Being There", year: 1979, definitive: true },
    { title: "Belfast", year: 2021 },
    { title: "Ben Is Back", year: 2018 },
    { title: "Beowulf", year: 2007 },
    { title: "Bicycle Thieves", year: 1948, definitive: true },
    { title: "The Big Lebowski", year: 1998, definitive: true },
    { title: "Big Eyes", year: 2014 },
    { title: "The Big Short", year: 2015 },
    { title: "Black Hawk Down", year: 2001 },
    { title: "Black Mirror: Bandersnatch", year: 2018 },
    { title: "Black Narcissus", year: 1947, definitive: true },
    { title: "Black Panther", year: 2018 },
    { title: "Black Panther: Wakanda Forever", year: 2022 },
    { title: "Black Phone", year: 2021 },
    { title: "Blade Runner", year: 1982, definitive: true },
    { title: "Blade Runner 2049", year: 2017 },
    { title: "Blackkklansman", year: 2018 },
    { title: "Blow Out", year: 1981, definitive: true },
    { title: "Blue Jasmine", year: 2013 },
    { title: "Blue Velvet", year: 1986, definitive: true },
    { title: "Bohemian Rhapsody", year: 2018 },
    { title: "Bone Tomahawk", year: 2015 },
    { title: "Born in China", year: 2017 },
    { title: "Brazil", year: 1985, definitive: true },
    { title: "The Bridge on the River Kwai", year: 1957, definitive: true },
    { title: "Brigsby Bear", year: 2017 },
    { title: "The Brood", year: 1979 },
    { title: "The Brutalist", year: 2024 },
    { title: "Brute Force", year: 1947, definitive: true },
    { title: "Bullet Train", year: 2022 },
    { title: "Byzantium", year: 2013 },
  ],
  C: [
    { title: "C'mon C'mon", year: 2021 },
    { title: "Cabaret", year: 1972, definitive: true },
    { title: "The Cabin in the Woods", year: 2012 },
    { title: "The Cabinet of Dr. Caligari", year: 1920, definitive: true },
    { title: "Caché", year: 2005, definitive: true },
    { title: "Call Me by Your Name", year: 2017 },
    { title: "Calvary", year: 2014 },
    { title: "Captain America: Civil War", year: 2016 },
    { title: "Captain America: The First Avenger", year: 2011 },
    { title: "Captain America: The Winter Soldier", year: 2014 },
    { title: "Captain Fantastic", year: 2016 },
    { title: "Captain Marvel", year: 2019 },
    { title: "Carol", year: 2015 },
    { title: "Casablanca", year: 1942, definitive: true },
    { title: "Casino Royale", year: 2006 },
    { title: "Casualties of War", year: 1989 },
    { title: "Certain Women", year: 2016 },
    { title: "Changeling", year: 2008 },
    { title: "Chinatown", year: 1974, definitive: true },
    { title: "Chum", year: 2026 },
    { title: "Citizen Kane", year: 1941, definitive: true },
    { title: "Cloverfield", year: 2008 },
    { title: "Cold War", year: 2018 },
    { title: "Collateral", year: 2004 },
    { title: "Come and See", year: 1985, definitive: true },
    { title: "Conclave", year: 2024 },
    { title: "The Conjuring", year: 2013 },
    { title: "Contact", year: 1997 },
    { title: "Contagion", year: 2011 },
    { title: "The Conversation", year: 1974, definitive: true },
    { title: "Corporate Retreat", year: 2026 },
    { title: "Crimes and Misdemeanors", year: 1989, definitive: true },
    { title: "Crouching Tiger, Hidden Dragon", year: 2000, definitive: true },
    { title: "The Crown", year: 2016 },
    { title: "Cyrus", year: 2010 },
  ],
  D: [
    { title: "Da 5 Bloods", year: 2020 },
    { title: "Dallas Buyers Club", year: 2013 },
    { title: "Dancer in the Dark", year: 2000, definitive: true },
    { title: "The Dark Knight", year: 2008, definitive: true },
    { title: "The Dark Knight Rises", year: 2012 },
    { title: "Darkest Hour", year: 2017 },
    { title: "David Byrne's American Utopia", year: 2020 },
    { title: "The Dead Zone", year: 1983 },
    { title: "Dead Ringers", year: 1988 },
    { title: "Deadpool", year: 2016 },
    { title: "Deadpool & Wolverine", year: 2024 },
    { title: "Dheepan", year: 2015 },
    { title: "Diner", year: 1982 },
    { title: "Doctor Strange", year: 2016 },
    { title: "Don't Look Now", year: 1973, definitive: true },
    { title: "Donnie Darko", year: 2001 },
    { title: "Drive", year: 2011 },
    { title: "Drive My Car", year: 2021, definitive: true },
    { title: "Dune", year: 2021 },
    { title: "Dune: Part Two", year: 2024 },
  ],
  E: [
    { title: "Eastern Promises", year: 2007 },
    { title: "Edge of Tomorrow", year: 2014 },
    { title: "Eighth Grade", year: 2018 },
    { title: "Election", year: 1999 },
    { title: "Elephant", year: 2003, definitive: true },
    { title: "Elvis", year: 2022 },
    { title: "Empiricism", year: 2023 },
    { title: "Enemy", year: 2013 },
    { title: "Eternal Sunshine of the Spotless Mind", year: 2004, definitive: true },
    { title: "Everything Everywhere All at Once", year: 2022 },
    { title: "Evil Dead Rise", year: 2023 },
    { title: "The Exorcist", year: 1973, definitive: true },
    { title: "Ex Machina", year: 2015 },
  ],
  F: [
    { title: "Faces Places", year: 2017 },
    { title: "Fahrenheit 9/11", year: 2004 },
    { title: "The Fall", year: 2006 },
    { title: "Fantastic Mr. Fox", year: 2009 },
    { title: "Far from Heaven", year: 2002, definitive: true },
    { title: "Fargo", year: 1996, definitive: true },
    { title: "Fellini Satyricon", year: 1969, definitive: true },
    { title: "The Firm", year: 1993 },
    { title: "First Man", year: 2018 },
    { title: "First Reformed", year: 2017, definitive: true },
    { title: "Fish Tank", year: 2009 },
    { title: "Fitzcarraldo", year: 1982, definitive: true },
    { title: "The Florida Project", year: 2017 },
    { title: "Flowers of War", year: 2011 },
    { title: "Force Majeure", year: 2014 },
    { title: "Ford v Ferrari", year: 2019 },
    { title: "Foreign Correspondent", year: 1940 },
    { title: "Frances Ha", year: 2012 },
    { title: "Frankenweenie", year: 2012 },
    { title: "Free Guy", year: 2021 },
    { title: "The French Dispatch", year: 2021 },
    { title: "Fruitvale Station", year: 2013 },
    { title: "Full Metal Jacket", year: 1987, definitive: true },
  ],
  G: [
    { title: "Gamera vs. Barugon", year: 1966 },
    { title: "Get Out", year: 2017, definitive: true },
    { title: "Ghost World", year: 2001 },
    { title: "Ghostbusters", year: 1984 },
    { title: "Ghostbusters: Afterlife", year: 2021 },
    { title: "Gladiator", year: 2000 },
    { title: "Gladiator II", year: 2024 },
    { title: "The Godfather", year: 1972, definitive: true },
    { title: "The Godfather Part II", year: 1974, definitive: true },
    { title: "Godzilla", year: 2014 },
    { title: "Godzilla Minus One", year: 2023 },
    { title: "Gone Girl", year: 2014 },
    { title: "Good Time", year: 2017 },
    { title: "Good Will Hunting", year: 1997 },
    { title: "Goodfellas", year: 1990, definitive: true },
    { title: "Gravity", year: 2013 },
    { title: "The Grand Budapest Hotel", year: 2014 },
    { title: "Green Book", year: 2018 },
    { title: "Green Room", year: 2015 },
    { title: "Gremlins", year: 1984 },
    { title: "Guardians of the Galaxy", year: 2014 },
  ],
  H: [
    { title: "Hacksaw Ridge", year: 2016 },
    { title: "Halloween", year: 1978, definitive: true },
    { title: "Hamlet", year: 1948, definitive: true },
    { title: "Happiness", year: 1998, definitive: true },
    { title: "The Happening", year: 2008 },
    { title: "Happy-Go-Lucky", year: 2008 },
    { title: "Hard Eight", year: 1996 },
    { title: "The Hate U Give", year: 2018 },
    { title: "Hereditary", year: 2018 },
    { title: "The High Note", year: 2020 },
    { title: "A History of Violence", year: 2005, definitive: true },
    { title: "Honey Boy", year: 2019 },
    { title: "The Hours", year: 2002 },
    { title: "House of Flying Daggers", year: 2004 },
    { title: "How to Train Your Dragon", year: 2010 },
    { title: "Hugo", year: 2011 },
    { title: "The Hunt", year: 2020 },
    { title: "The Hurt Locker", year: 2008, definitive: true },
    { title: "Hustle", year: 2022 },
  ],
  I: [
    { title: "I, Daniel Blake", year: 2016 },
    { title: "I'm Still Here", year: 2024 },
    { title: "Inception", year: 2010 },
    { title: "Incredibles 2", year: 2018 },
    { title: "The Incredibles", year: 2004 },
    { title: "Inherent Vice", year: 2014, definitive: true },
    { title: "Inside Llewyn Davis", year: 2013 },
    { title: "Interstellar", year: 2014 },
    { title: "In the Bedroom", year: 2001, definitive: true },
    { title: "In the Mood for Love", year: 2000, definitive: true },
    { title: "Io Capitano", year: 2023 },
    { title: "It", year: 2017 },
    { title: "It Comes at Night", year: 2017 },
    { title: "It Follows", year: 2015 },
  ],
  J: [
    { title: "Jackie", year: 2016 },
    { title: "Joker", year: 2019 },
    { title: "Joker: Folie à Deux", year: 2024 },
    { title: "John Wick", year: 2014 },
    { title: "John Wick: Chapter 4", year: 2023 },
    { title: "Judas and the Black Messiah", year: 2021 },
    { title: "Jurassic Park", year: 1993, definitive: true },
    { title: "Jurassic World", year: 2015 },
  ],
  K: [
    { title: "Killing Ground", year: 2017 },
    { title: "Killing of a Sacred Deer", year: 2017 },
    { title: "Knives Out", year: 2019 },
    { title: "The Knick", year: 2014 },
    { title: "Kramer vs. Kramer", year: 1979, definitive: true },
  ],
  L: [
    { title: "La La Land", year: 2016 },
    { title: "Last Night in Soho", year: 2021 },
    { title: "Lawrence of Arabia", year: 1962, definitive: true },
    { title: "Leave No Trace", year: 2018 },
    { title: "The Lighthouse", year: 2019 },
    { title: "Lincoln", year: 2012 },
    { title: "The Lives of Others", year: 2006, definitive: true },
    { title: "Loki", year: 2021 },
    { title: "Lone Survivor", year: 2013 },
    { title: "The Lobster", year: 2015 },
    { title: "Logan", year: 2017 },
    { title: "Luca", year: 2021 },
    { title: "Lucky", year: 2017 },
    { title: "Lust, Caution", year: 2007, definitive: true },
  ],
  M: [
    { title: "M", year: 1931, definitive: true },
    { title: "Mad Max: Fury Road", year: 2015, definitive: true },
    { title: "Magnolia", year: 1999, definitive: true },
    { title: "The Man Who Wasn't There", year: 2001, definitive: true },
    { title: "Manchester by the Sea", year: 2016 },
    { title: "Marriage Story", year: 2019 },
    { title: "The Master", year: 2012, definitive: true },
    { title: "McCabe & Mrs. Miller", year: 1971, definitive: true },
    { title: "Midsommar", year: 2019 },
    { title: "Minari", year: 2020 },
    { title: "Minority Report", year: 2002 },
    { title: "Mission: Impossible – Fallout", year: 2018 },
    { title: "Moonlight", year: 2016, definitive: true },
    { title: "Mother!", year: 2017 },
    { title: "Mulholland Drive", year: 2001, definitive: true },
    { title: "The Mule", year: 2018 },
  ],
  N: [
    { title: "Nebraska", year: 2013 },
    { title: "Network", year: 1976, definitive: true },
    { title: "Never Rarely Sometimes Always", year: 2020 },
    { title: "A New Leaf", year: 1971 },
    { title: "The Nightingale", year: 2018 },
    { title: "Nightmare Alley", year: 2021 },
    { title: "No Country for Old Men", year: 2007, definitive: true },
    { title: "Noah", year: 2014 },
    { title: "Nomadland", year: 2020 },
    { title: "North by Northwest", year: 1959, definitive: true },
    { title: "Nosferatu", year: 2024 },
    { title: "Nostalghia", year: 1983, definitive: true },
  ],
  O: [
    { title: "Oldboy", year: 2003, definitive: true },
    { title: "Once Upon a Time in America", year: 1984, definitive: true },
    { title: "Once Upon a Time in Hollywood", year: 2019 },
    { title: "Oppenheimer", year: 2023 },
    { title: "The Others", year: 2001 },
  ],
  P: [
    { title: "Pan's Labyrinth", year: 2006, definitive: true },
    { title: "Parasite", year: 2019, definitive: true },
    { title: "Passenger", year: 2026 },
    { title: "Past Lives", year: 2023 },
    { title: "The Phantom of the Opera", year: 1925, definitive: true },
    { title: "The Philadelphia Story", year: 1940, definitive: true },
    { title: "The Piano", year: 1993, definitive: true },
    { title: "Portrait of a Lady on Fire", year: 2019, definitive: true },
    { title: "Power Ballad", year: 2026 },
    { title: "Pressure", year: 2026 },
    { title: "The Power of the Dog", year: 2021 },
    { title: "Prisoners", year: 2013 },
    { title: "Promising Young Woman", year: 2020 },
  ],
  Q: [
    { title: "The Queen", year: 2006 },
    { title: "Queen & Slim", year: 2019 },
    { title: "Quiet City", year: 2007 },
    { title: "Quiz Show", year: 1994 },
  ],
  R: [
    { title: "Raging Bull", year: 1980, definitive: true },
    { title: "Rashomon", year: 1950, definitive: true },
    { title: "The Raid", year: 2011 },
    { title: "Rear Window", year: 1954, definitive: true },
    { title: "Red River", year: 1948 },
    { title: "Red Sorghum", year: 1988, definitive: true },
    { title: "Renoir", year: 2026 },
    { title: "Repo Man", year: 1984 },
    { title: "Roma", year: 2018 },
    { title: "Rosemary's Baby", year: 1968, definitive: true },
    { title: "The Rover", year: 2014 },
    { title: "Run Lola Run", year: 1998 },
  ],
  S: [
    { title: "Samaritan", year: 2022 },
    { title: "Schindler's List", year: 1993, definitive: true },
    { title: "Scream", year: 1996 },
    { title: "Se7en", year: 1995, definitive: true },
    { title: "The Searchers", year: 1956, definitive: true },
    { title: "Seconds", year: 1966, definitive: true },
    { title: "Shame", year: 2011 },
    { title: "Shiva Baby", year: 2020 },
    { title: "Sicario", year: 2015 },
    { title: "Silence", year: 2016, definitive: true },
    { title: "The Silence of the Lambs", year: 1991, definitive: true },
    { title: "Singin' in the Rain", year: 1952, definitive: true },
    { title: "Snowpiercer", year: 2013 },
    { title: "Somewhere", year: 2010 },
    { title: "Son of Saul", year: 2015, definitive: true },
    { title: "Sorry to Bother You", year: 2018 },
    { title: "Soul", year: 2020 },
    { title: "Spencer", year: 2021 },
    { title: "Stalker", year: 1979, definitive: true },
    { title: "Star Wars: The Force Awakens", year: 2015 },
    { title: "Succession", year: 2018 },
    { title: "Sunflower", year: 2026 },
    { title: "Sunshine", year: 2007, definitive: true },
    { title: "Suspiria", year: 1977, definitive: true },
  ],
  T: [
    { title: "Talk to Her", year: 2002, definitive: true },
    { title: "Tangerine", year: 2015 },
    { title: "Taxi Driver", year: 1976, definitive: true },
    { title: "The Thing", year: 1982, definitive: true },
    { title: "The Three Colors Trilogy", year: 1993, definitive: true },
    { title: "Tenet", year: 2020 },
    { title: "Tár", year: 2022 },
    { title: "There Will Be Blood", year: 2007, definitive: true },
    { title: "This Is 40", year: 2012 },
    { title: "Toni Morrison: The Pieces I Am", year: 2019 },
    { title: "Top Gun: Maverick", year: 2022 },
    { title: "Topsy-Turvy", year: 1999, definitive: true },
    { title: "Toy Story 4", year: 2019 },
    { title: "Trainspotting", year: 1996 },
    { title: "Triangle of Sadness", year: 2022 },
    { title: "The Turin Horse", year: 2011, definitive: true },
    { title: "Turning Red", year: 2022 },
  ],
  U: [
    { title: "Uncut Gems", year: 2019 },
    { title: "Under the Skin", year: 2014, definitive: true },
    { title: "Unhinged", year: 2020 },
    { title: "Us", year: 2019 },
  ],
  V: [
    { title: "Vanya on 42nd Street", year: 1994, definitive: true },
    { title: "Vengeance", year: 2022 },
    { title: "Vertigo", year: 1958, definitive: true },
    { title: "Violence Voyager", year: 2018 },
    { title: "The Virgin Suicides", year: 1999 },
    { title: "Vox Lux", year: 2018 },
  ],
  W: [
    { title: "The Walk", year: 2015 },
    { title: "Wall-E", year: 2008, definitive: true },
    { title: "Waves", year: 2019 },
    { title: "Weekend", year: 1967, definitive: true },
    { title: "Werewolf by Night", year: 2022 },
    { title: "Whiplash", year: 2014 },
    { title: "Widows", year: 2018 },
    { title: "Wild", year: 2014 },
    { title: "Wild Tales", year: 2014 },
    { title: "The Wild Robot", year: 2024 },
    { title: "Willy Wonka & the Chocolate Factory", year: 1971 },
    { title: "The Witch", year: 2015 },
    { title: "Women Talking", year: 2022 },
    { title: "Wonder Woman", year: 2017 },
    { title: "The Worst Person in the World", year: 2021 },
  ],
  X: [
    { title: "X", year: 2022 },
    { title: "X-Men: Days of Future Past", year: 2014 },
    { title: "X-Men: First Class", year: 2011 },
  ],
  Y: [
    { title: "A Year in a Field", year: 2023 },
    { title: "Yi Yi", year: 2000, definitive: true },
    { title: "You Were Never Really Here", year: 2017, definitive: true },
  ],
  Z: [
    { title: "Z", year: 1969, definitive: true },
    { title: "Zero Dark Thirty", year: 2012 },
    { title: "Zodiac", year: 2007, definitive: true },
    { title: "Zombieland", year: 2009 },
  ],
};

export const LETTERS = ["#", ...Array.from({ length: 26 }, (_, i) => String.fromCharCode(65 + i))];
