// ©2004-2026 Deep Focus Review. All rights reserved.
// Content sourced from deepfocusreview.com as of June 25, 2026

// SITE_REVIEWS[0] = hero, slice(1) = "New Reviews" grid
export const SITE_REVIEWS = [
  {
    id: 1,
    title: "In the Hand of Dante",
    director: "Julian Schnabel",
    year: 2026,
    rating: "★★",
    category: "FILM REVIEW",
    summary: "A beautiful but incohesive disappointment — Schnabel's dual narrative across centuries is visually striking but meanders without cohering into the transcendent vision it reaches for.",
    image: "https://www.deepfocusreview.com/wp-content/uploads/2026/06/In-the-Hand-of-Dante-movie-still-2026.png",
    author: "Brian Eggert",
    date: "June 24, 2026",
    label: "NEW",
  },
  {
    id: 2,
    title: "The Saviors",
    director: "Kevin Hamedani",
    year: 2026,
    rating: "★★★",
    category: "FILM REVIEW",
    summary: "Hamedani's funny, paranoid comedy smartly plays with the audience's inadvertent prejudices before confronting them with reality.",
    image: "https://www.deepfocusreview.com/wp-content/uploads/2026/06/The-Saviors-2026-movie-still-1.png",
    author: "Brian Eggert",
    date: "June 20, 2026",
    label: "NEW",
  },
  {
    id: 3,
    title: "The Death of Robin Hood",
    director: "Michael Sarnoski",
    year: 2026,
    rating: "★★★½",
    category: "FILM REVIEW",
    summary: "A remarkably shot demystification of the legend — Sarnoski reimagines the archer as a medieval outlaw mythologized for clashing with oppressive royals.",
    image: "https://www.deepfocusreview.com/wp-content/uploads/2026/06/The-Death-of-Robin-Hood-movie-still-2.png",
    author: "Brian Eggert",
    date: "June 17, 2026",
    label: "NEW",
  },
  {
    id: 4,
    title: "Toy Story 5",
    director: "Andrew Stanton & Kenna Harris",
    year: 2026,
    rating: "★★★½",
    category: "FILM REVIEW",
    summary: "Essential, funny, and heartwarming — Pixar delivers a sequel nobody knew they needed, exploring how children's play is being replaced by screens.",
    image: "https://www.deepfocusreview.com/wp-content/uploads/2026/06/Toy-Story-5-movie-still-5.png",
    author: "Brian Eggert",
    date: "June 13, 2026",
    label: "NEW",
  },
  {
    id: 5,
    title: "Leviticus",
    director: "Adrian Chiarella",
    year: 2026,
    rating: "★★★",
    category: "FILM REVIEW",
    summary: "A chilling story about what it feels like when your natural desires have been demonized — a frightening yarn about conversion therapy told with shattering precision.",
    image: "https://www.deepfocusreview.com/wp-content/uploads/2026/06/Leviticus-movie-still-1-e1781153335609.png",
    author: "Brian Eggert",
    date: "June 10, 2026",
    label: "NEW",
  },
];

// Right sidebar "Recently Reviewed"
export const SITE_SECONDARY_REVIEWS = [
  {
    title: "The Innocents",
    director: "Eskil Vogt",
    rating: "★★★½",
    snippet: "A chilling story of superpowered children — Vogt's slow-burn horror is as quietly devastating as it is formally assured.",
    image: "https://www.deepfocusreview.com/wp-content/uploads/2026/06/The-Innocents-2021-movie-still.png",
  },
  {
    title: "Forastera",
    director: "Lucía Aleñar Iglesias",
    rating: "★★★½",
    snippet: "A delicate ghost story about how grief and memory can conspire to become almost like a possession.",
    image: "https://www.deepfocusreview.com/wp-content/uploads/2026/06/Forastera-movie-still-1.png",
  },
  {
    title: "Disclosure Day",
    director: "Steven Spielberg",
    rating: "★★★★",
    snippet: "Perhaps no filmmaker is more skilled at capturing his audience — Spielberg's alien-contact epic is his most expansive work in years.",
    image: "https://www.deepfocusreview.com/wp-content/uploads/2026/06/Disclosure-Day-movie-still-4.png",
  },
  {
    title: "Power Ballad",
    director: "John Carney",
    rating: "★★★",
    snippet: "A film about finding the balance between artistic integrity and personal fulfillment — Carney's best since Begin Again.",
    image: "https://www.deepfocusreview.com/wp-content/uploads/2026/05/Power-Ballad-Movie-Poster.png",
  },
];

// Poster grid sidebar (used by mobile and alternate layouts)
export const SITE_SIDEBAR_REVIEWS = [
  { title: "The Saviors", year: 2026, rating: "★★★", image: "https://www.deepfocusreview.com/wp-content/uploads/2026/06/The-Saviors-2026-movie-still-1.png" },
  { title: "Toy Story 5", year: 2026, rating: "★★★½", image: "https://www.deepfocusreview.com/wp-content/uploads/2026/06/Toy-Story-5-movie-still-5.png" },
  { title: "Forastera", year: 2026, rating: "★★★½", image: "https://www.deepfocusreview.com/wp-content/uploads/2026/06/Forastera-movie-still-1.png" },
];

export const SITE_DEFINITIVES_FILMS = [
  {
    id: 1,
    title: "The Philadelphia Story",
    year: 1940,
    director: "George Cukor",
    date: "May 26, 2026",
    excerpt: "Katharine Hepburn engineered the ultimate comeback with The Philadelphia Story — one of the finest romantic comedies from Hollywood's Golden Age and a searching examination of impossible standards.",
    image: "https://www.deepfocusreview.com/wp-content/uploads/2026/05/The-Philadelphia-Story-movie-poster.png",
    decade: "1940s",
  },
  {
    id: 2,
    title: "Red Sorghum",
    year: 1988,
    director: "Zhang Yimou",
    date: "April 21, 2026",
    excerpt: "Zhang Yimou's debut feature is a sensory assault of red earth and ritual — a film about desire, violence, and survival rendered in images of startling visual force.",
    image: "https://www.deepfocusreview.com/wp-content/uploads/2024/07/red-sorghum-1987-movie-still-1-e1776702132482-300x168.jpg",
    decade: "1980s",
  },
  {
    id: 3,
    title: "Stalker",
    year: 1979,
    director: "Andrei Tarkovsky",
    date: "March 31, 2026",
    excerpt: "Tarkovsky's great film of spiritual yearning moves with the pace of a dream through a forbidden zone — a meditation on faith, hope, and the unknowable.",
    image: "https://www.deepfocusreview.com/wp-content/uploads/2025/04/stalker-7-300x169.png",
    decade: "1970s",
  },
  {
    id: 4,
    title: "Sunshine",
    year: 2007,
    director: "Danny Boyle",
    date: "March 22, 2026",
    excerpt: "Danny Boyle's overlooked sci-fi masterwork charts a crew's mission to reignite a dying sun — and finds in that premise an almost unbearable meditation on sacrifice and hubris.",
    image: "https://www.deepfocusreview.com/wp-content/uploads/2026/03/Sunshine-2007-movie-still-2-300x169.png",
    decade: "2000s",
  },
  {
    id: 5,
    title: "M",
    year: 1931,
    director: "Fritz Lang",
    date: "March 10, 2026",
    excerpt: "Fritz Lang's first sound film remains among the most morally and formally complex crime pictures ever made — a city-wide manhunt that implicates everyone, including the audience.",
    image: "https://www.deepfocusreview.com/wp-content/uploads/2025/03/M-1931-still-1-300x169.png",
    decade: "1930s",
  },
  {
    id: 6,
    title: "Magnolia",
    year: 1999,
    director: "Paul Thomas Anderson",
    date: "February 24, 2026",
    excerpt: "Paul Thomas Anderson's three-hour mosaic of Los Angeles loneliness and coincidence remains one of American cinema's most fearlessly emotional works.",
    image: "https://www.deepfocusreview.com/wp-content/uploads/2026/02/Margnolia-1999-movie-still-11-300x169.png",
    decade: "1990s",
  },
  {
    id: 7,
    title: "Bad Day at Black Rock",
    year: 1955,
    director: "John Sturges",
    date: "February 11, 2026",
    excerpt: "A one-armed stranger arrives in a desert town. Sturges's CinemaScope western is a taut, allegorical thriller about guilt, complicity, and the silence of bystanders.",
    image: "https://www.deepfocusreview.com/wp-content/uploads/2026/01/Bad-Day-at-Black-Rock-movie-still-1-300x169.png",
    decade: "1950s",
  },
  {
    id: 8,
    title: "All About My Mother",
    year: 1999,
    director: "Pedro Almodóvar",
    date: "February 3, 2026",
    excerpt: "Almodóvar's most emotionally generous film follows a grieving mother into a world of performance, solidarity, and transformation — a masterwork of compassionate filmmaking.",
    image: "https://www.deepfocusreview.com/wp-content/uploads/2025/02/All-About-My-Mother-1-e1739974031973-300x167.png",
    decade: "1990s",
  },
  {
    id: 9,
    title: "Brute Force",
    year: 1947,
    director: "Jules Dassin",
    date: "January 25, 2026",
    excerpt: "Jules Dassin's ferocious prison noir — suppressed by the censors for its violence and politics — is one of Hollywood's most radical and uncompromising films.",
    image: "https://www.deepfocusreview.com/wp-content/uploads/2026/01/Brute-Force-1947-movie-still-1-300x169.png",
    decade: "1940s",
  },
];
