// Design-variety LENS DECK v1 — DRAFT for tuning. See docs/design-variety-spec.md §3–5.
//
// NOT WIRED IN YET. The P1 sampler (`direction.cjs`) will consume this: pick a lens
// weighted by the axes + brand/tone fit + anti-repetition memory, then draw each motif
// slot from that lens's eligible set. Everything here is prompt-facing content — the
// `directives` strings become the "Design direction" block in buildDesignPrompt, so
// they are written to be dropped into a prompt verbatim.
//
// House style applies (this is copy a person tunes and the model reads): typographic
// apostrophes, no em-dashes.

// ── Axis model: the designer-facing knobs. Discrete labeled stops (index 0..3), left
//    to right. A lens's `axisAffinity` names its natural stop on each; the sampler uses
//    the distance between the designer's knob and the lens affinity as a weight. ──
const AXES = {
  convention: ["common", "familiar", "bold", "experimental"], // how far off the centroid
  energy:     ["calm", "measured", "lively", "maximal"],       // intensity / density / contrast
  structure:  ["ordered", "balanced", "loose", "organic"],     // grid-strict → freeform
  era:        ["timeless", "classic", "current", "avant-garde"], // stylistic period reference
};

// Per-stop rubric phrases — the actual prompt text a knob position injects. These are
// lens-independent; the lens `directives` layer on top. (Draft; tune against real gens.)
const AXIS_RUBRIC = {
  convention: {
    common:       "Stay close to familiar, high-credibility marketing conventions.",
    familiar:     "Use a recognizable structure, but give it one considered, non-generic move.",
    bold:         "Break from the obvious layout; favor an unexpected structure or a signature moment.",
    experimental: "Depart deliberately from typical conventions: unconventional layout, unexpected type, distinctive motifs. Stay usable.",
  },
  energy: {
    calm:     "Quiet and spacious; few elements, soft contrast, lots of breathing room.",
    measured: "Composed and even; clear contrast without noise.",
    lively:   "Energetic; stronger contrast, scale jumps, and accent color.",
    maximal:  "Dense and loud; layered elements, big scale jumps, ornament, high contrast.",
  },
  structure: {
    ordered:  "Strict, visible grid; everything aligns; symmetry where it helps.",
    balanced: "A clear grid with deliberate breaks from it.",
    loose:    "Asymmetric and offset; the grid is a suggestion, not a cage.",
    organic:  "Freeform and hand-built; overlaps, irregular placement, no rigid columns.",
  },
  era: {
    timeless:      "Classic and durable; nothing that will date quickly.",
    classic:       "Lean on a specific past era's design language, done with intent.",
    current:       "Of-the-moment contemporary web craft.",
    "avant-garde": "Forward-looking and experimental; ahead of current trends.",
  },
};

// ── Motif slots (lever 2): the full option vocabulary per slot. Each lens declares a
//    coherent SUBSET in `motifEligibility`; the sampler only ever draws from that subset,
//    so a sample is never a mashup of incompatible tropes. Demoting an overused motif
//    (e.g. "numbered-index" eyebrows) to 1 option among several is how the "05 Connect"
//    repetition breaks — it stays authentic where a lens genuinely calls for it. ──
const MOTIFS = {
  // The little label above a section heading.
  eyebrow:       ["none", "numbered-index", "hairline-rule", "micro-caps", "icon-led", "oversized-index", "kicker-line", "tab-chip", "vertical-label"],
  // The hero / first-viewport archetype.
  hero:          ["split", "centered", "full-bleed", "type-only", "asymmetric", "editorial-cover", "collage", "boxed-frame", "split-diagonal"],
  // How sections pace down the page.
  sectionRhythm: ["uniform", "alternating", "escalating-density", "punctuated-by-fullbleed", "editorial-flow", "ribbon-bands", "sparse"],
  // How a set of features / items is laid out.
  featureLayout: ["cards", "rows", "stagger", "editorial-list", "grid-collage", "bento", "table", "carousel"],
  // What separates sections.
  divider:       ["none", "rule", "shape", "color-block", "overlap", "whitespace", "gradient-fade", "angled-cut"],
};

// Human phrasing for each motif slug, so the sampled choice reads as an instruction in
// the "Design direction" prompt block (renderDirectionPrompt). Prompt-facing content,
// kept with the deck so all the moat text moves together if this goes to the cloud.
const MOTIF_GLOSS = {
  eyebrow: {
    "none": "no small label above section headings",
    "numbered-index": "a numbered index above section headings (01, 02, 03)",
    "hairline-rule": "a thin hairline rule above section headings",
    "micro-caps": "a small all-caps label above section headings",
    "icon-led": "a small icon leading each section heading",
    "oversized-index": "an oversized number or index used as a graphic element by the heading",
    "kicker-line": "a short kicker phrase above the section heading",
    "tab-chip": "a small pill or tab-style chip label above the section heading",
    "vertical-label": "a rotated label running vertically alongside the section heading",
  },
  hero: {
    "split": "a split hero (headline on one side, visual on the other)",
    "centered": "a centered hero statement",
    "full-bleed": "a full-bleed hero (edge-to-edge image or color)",
    "type-only": "a type-only hero (the headline fills the first screen, no hero image)",
    "asymmetric": "an asymmetric, off-center hero composition",
    "editorial-cover": "an editorial-cover hero (magazine-style lead: strong headline plus a lead image)",
    "collage": "a collage hero (layered, overlapping elements)",
    "boxed-frame": "a hero framed inside a bordered panel or window",
    "split-diagonal": "a hero split along a diagonal, angled division between headline and visual",
  },
  sectionRhythm: {
    "uniform": "uniform, evenly paced sections",
    "alternating": "alternating section layouts (left/right or light/dark)",
    "escalating-density": "sections that escalate in density and intensity down the page",
    "punctuated-by-fullbleed": "regular sections punctuated by full-bleed moments",
    "editorial-flow": "an editorial flow where section width and density vary like magazine pages",
    "ribbon-bands": "full-width color bands that alternate down the page",
    "sparse": "very sparse pacing with large empty stretches between a few sections",
  },
  featureLayout: {
    "cards": "feature cards",
    "rows": "full-width feature rows",
    "stagger": "staggered, offset feature blocks",
    "editorial-list": "an editorial list (typographic, numbered or ruled)",
    "grid-collage": "a grid collage of items",
    "bento": "a bento grid of mixed-size tiles",
    "table": "a structured comparison or spec table",
    "carousel": "a horizontal carousel or slider of items",
  },
  divider: {
    "none": "no explicit dividers between sections",
    "rule": "thin rules between sections",
    "shape": "shaped dividers between sections",
    "color-block": "color-block transitions between sections",
    "overlap": "overlapping sections that bleed into each other",
    "whitespace": "generous whitespace as the only divider",
    "gradient-fade": "a soft gradient fade between sections",
    "angled-cut": "an angled or diagonal cut between sections",
  },
};

// ── Motif axis affinity (lever 2 weighting). A PARTIAL lean per option: only the axis
//    stops it actually expresses (unlisted axes don't affect its weight). The sampler
//    scores each of a lens's eligible options against the resolved axes and weights the
//    draw, so within one lens an ordered/calm design and a loose/maximal design get
//    DIFFERENT (coherent) motifs instead of a uniform coin-flip. Floors keep variety. ──
const MOTIF_AFFINITY = {
  eyebrow: {
    "none":            { energy: "calm", convention: "common" },
    "numbered-index":  { structure: "ordered", energy: "measured" },
    "hairline-rule":   { structure: "ordered", energy: "calm" },
    "micro-caps":      { convention: "familiar", energy: "measured" },
    "icon-led":        { energy: "lively", convention: "familiar" },
    "oversized-index": { energy: "maximal", convention: "bold" },
    "kicker-line":     { structure: "balanced", energy: "measured" },
    "tab-chip":        { era: "current", energy: "lively" },
    "vertical-label":  { convention: "bold", structure: "loose" },
  },
  hero: {
    "split":           { structure: "balanced", energy: "measured" },
    "centered":        { convention: "common", energy: "calm" },
    "full-bleed":      { energy: "lively" },
    "type-only":       { convention: "bold", structure: "loose" },
    "asymmetric":      { structure: "loose", convention: "bold" },
    "editorial-cover": { era: "classic", structure: "balanced" },
    "collage":         { structure: "organic", energy: "maximal" },
    "boxed-frame":     { structure: "ordered", era: "classic" },
    "split-diagonal":  { structure: "loose", convention: "bold" },
  },
  sectionRhythm: {
    "uniform":                 { structure: "ordered", energy: "measured" },
    "alternating":             { structure: "balanced", energy: "measured" },
    "escalating-density":      { energy: "maximal" },
    "punctuated-by-fullbleed": { energy: "lively" },
    "editorial-flow":          { structure: "loose", energy: "measured" },
    "ribbon-bands":            { energy: "lively", structure: "balanced" },
    "sparse":                  { energy: "calm", structure: "ordered" },
  },
  featureLayout: {
    "cards":          { convention: "common", structure: "ordered" },
    "rows":           { structure: "ordered", energy: "measured" },
    "stagger":        { structure: "loose", energy: "lively" },
    "editorial-list": { structure: "balanced", energy: "measured" },
    "grid-collage":   { energy: "maximal", structure: "organic" },
    "bento":          { era: "current", energy: "lively" },
    "table":          { convention: "common", structure: "ordered" },
    "carousel":       { era: "current", energy: "lively" },
  },
  divider: {
    "none":          { energy: "calm" },
    "rule":          { structure: "ordered", energy: "measured" },
    "shape":         { structure: "organic", energy: "lively" },
    "color-block":   { energy: "maximal", convention: "bold" },
    "overlap":       { structure: "organic", energy: "maximal" },
    "whitespace":    { energy: "calm", structure: "balanced" },
    "gradient-fade": { era: "current", energy: "lively" },
    "angled-cut":    { convention: "bold", structure: "loose" },
  },
};

// ── The deck. 23 lenses: 14 general compositional directions that SPAN the axes (a Common
//    anchor for conservative clients through to Experimental), then 9 art/design MOVEMENTS
//    (Bauhaus, Art Deco, …, flagged with `autoWeight` so they stay light in random variety
//    but surface fully when named or picked). Individually distinct + usable; grow over
//    time, this is the moat. ──
const LENSES = [
  {
    id: "corporate-confident",
    label: "Corporate Confident",
    description: "The credible centroid done well. Polished, trustworthy, unfussy. The safe end of the Convention axis, the release valve for conservative clients.",
    axisAffinity: { convention: "common", energy: "calm", structure: "ordered", era: "timeless" },
    fitTags: ["finance", "legal", "b2b", "enterprise", "healthcare", "insurance", "consulting"],
    directives: {
      grid: "Clean 12-column grid, comfortable margins, predictable alignment.",
      type: "One professional sans plus an optional restrained serif for headings. Clear size hierarchy.",
      sectionRhythm: "Even, well-spaced sections; one confident accent moment, not many.",
      heroBias: "Split hero (headline + supporting visual) or a calm centered statement.",
      motifVocabulary: "Subtle cards, soft shadows used sparingly, a single brand accent, real photography.",
      density: "medium",
      dos: ["Look established and legible", "Earn trust through polish and restraint"],
      donts: ["No trend-chasing", "Avoid the exact six-section clone; vary at least the rhythm and eyebrow"],
    },
    motifEligibility: {
      eyebrow: ["micro-caps", "hairline-rule", "none", "kicker-line", "tab-chip"],
      hero: ["split", "centered", "full-bleed"],
      sectionRhythm: ["uniform", "alternating", "sparse"],
      featureLayout: ["cards", "rows", "bento", "table"],
      divider: ["whitespace", "rule", "color-block"],
    },
  },
  {
    id: "swiss",
    label: "Swiss / International",
    description: "Objective, grid-driven, typographic. Confidence through precision and restraint.",
    axisAffinity: { convention: "familiar", energy: "measured", structure: "ordered", era: "timeless" },
    fitTags: ["tech", "editorial", "b2b", "architecture", "finance", "design-studio"],
    directives: {
      grid: "Strict, almost visible column grid; consistent gutters; everything snaps to it.",
      type: "A single clean grotesque. Hierarchy by size and weight only. Flush-left, ragged-right.",
      sectionRhythm: "Uniform sections; the grid, not ornament, makes the rhythm.",
      heroBias: "Type-led or asymmetric; headline placed with mathematical care and generous margin.",
      motifVocabulary: "Hairline rules, index numbers, precise captions, vast white space. No shadows, gradients, or rounded corners.",
      density: "low-to-medium",
      dos: ["Let alignment and whitespace carry it", "Use scale and weight for hierarchy"],
      donts: ["No decorative flourishes", "No drop shadows or gradients", "Don't center everything"],
    },
    motifEligibility: {
      eyebrow: ["numbered-index", "hairline-rule", "micro-caps", "none", "vertical-label"],
      hero: ["type-only", "asymmetric", "split"],
      sectionRhythm: ["uniform", "alternating", "sparse"],
      featureLayout: ["rows", "editorial-list", "grid-collage", "table"],
      divider: ["rule", "whitespace", "none"],
    },
  },
  {
    id: "editorial",
    label: "Editorial / Magazine",
    description: "A magazine spread on the web: strong type, mixed columns, deliberate asymmetry, imagery treated as content.",
    axisAffinity: { convention: "familiar", energy: "measured", structure: "balanced", era: "classic" },
    fitTags: ["media", "fashion", "lifestyle", "agency", "publishing", "culture", "food"],
    directives: {
      grid: "Editorial grid with varied column spans; pull-quotes and images break the measure.",
      type: "A characterful serif or high-contrast display for headings, clean sans for body. Big headline scale.",
      sectionRhythm: "Editorial flow: sections vary in width and density like magazine pages.",
      heroBias: "Editorial-cover or asymmetric; a commanding headline, a strong lead image, a dateline feel.",
      motifVocabulary: "Drop caps, pull-quotes, captions, column rules, oversized folios.",
      density: "medium",
      dos: ["Treat type as the lead voice", "Vary column width for rhythm"],
      donts: ["No uniform card grids", "Don't center every heading"],
    },
    motifEligibility: {
      eyebrow: ["kicker-line", "oversized-index", "micro-caps", "hairline-rule", "vertical-label"],
      hero: ["editorial-cover", "asymmetric", "split"],
      sectionRhythm: ["editorial-flow", "alternating", "punctuated-by-fullbleed"],
      featureLayout: ["editorial-list", "stagger", "grid-collage"],
      divider: ["rule", "whitespace", "overlap"],
    },
  },
  {
    id: "boutique-minimal",
    label: "Boutique Minimal",
    description: "Luxury restraint. Vast whitespace, small refined type, very few elements, everything intentional.",
    axisAffinity: { convention: "familiar", energy: "calm", structure: "balanced", era: "timeless" },
    fitTags: ["luxury", "fashion", "beauty", "architecture", "hospitality", "jewelry", "wellness"],
    directives: {
      grid: "Spare, balanced composition; enormous margins; few elements per view.",
      type: "Delicate, refined type at modest sizes; wide letter-spacing on labels.",
      sectionRhythm: "Calm and slow; generous emptiness between a small number of sections.",
      heroBias: "Full-bleed image with a whisper of type, or type-only with immense space.",
      motifVocabulary: "Thin rules, letter-spaced micro-labels, monochrome or near-monochrome, one hero image.",
      density: "low",
      dos: ["Make emptiness the feature", "Restrain the palette and the element count"],
      donts: ["No clutter", "No loud color", "Nothing that looks mass-market"],
    },
    motifEligibility: {
      eyebrow: ["micro-caps", "none", "hairline-rule"],
      hero: ["full-bleed", "type-only", "asymmetric", "boxed-frame"],
      sectionRhythm: ["uniform", "punctuated-by-fullbleed", "sparse"],
      featureLayout: ["rows", "editorial-list", "stagger"],
      divider: ["whitespace", "none", "rule"],
    },
  },
  {
    id: "warm-humanist",
    label: "Warm Humanist",
    description: "Friendly and approachable. Humanist type, soft palettes, real people, rounded edges without being childish.",
    axisAffinity: { convention: "common", energy: "measured", structure: "balanced", era: "current" },
    fitTags: ["healthcare", "education", "nonprofit", "community", "hospitality", "wellness", "consumer"],
    directives: {
      grid: "Comfortable, forgiving grid; soft corners; nothing sharp or cold.",
      type: "A humanist sans or a warm serif; generous line height; conversational scale.",
      sectionRhythm: "Even and welcoming; photography of people recurs.",
      heroBias: "Split with a warm human image, or centered with an inviting line.",
      motifVocabulary: "Rounded cards, soft shadows, warm accent color, candid photography, gentle illustration.",
      density: "medium",
      dos: ["Feel human and reassuring", "Use real, warm imagery"],
      donts: ["Nothing austere or corporate-cold", "Avoid harsh contrast"],
    },
    motifEligibility: {
      eyebrow: ["icon-led", "micro-caps", "kicker-line", "none", "tab-chip"],
      hero: ["split", "centered", "collage"],
      sectionRhythm: ["uniform", "alternating", "ribbon-bands"],
      featureLayout: ["cards", "rows", "stagger", "carousel"],
      divider: ["shape", "whitespace", "color-block"],
    },
  },
  {
    id: "gallery-curatorial",
    label: "Gallery / Curatorial",
    description: "Museum-like. Image-led, generous, restrained chrome, the content presented as art.",
    axisAffinity: { convention: "familiar", energy: "calm", structure: "balanced", era: "timeless" },
    fitTags: ["art", "photography", "portfolio", "luxury", "culture", "architecture", "design-studio"],
    directives: {
      grid: "Image-first composition; work sits in generous frames; chrome recedes.",
      type: "Quiet, small type that never competes with the imagery; captions in fine print.",
      sectionRhythm: "Slow, punctuated by full-bleed imagery; space to breathe between works.",
      heroBias: "Full-bleed or collage of the work itself, minimal overlaid type.",
      motifVocabulary: "Fine captions, index numbers, thin frames, monochrome chrome around rich images.",
      density: "low",
      dos: ["Let the imagery lead", "Keep the interface nearly invisible"],
      donts: ["No heavy UI chrome", "Don't crowd the work"],
    },
    motifEligibility: {
      eyebrow: ["numbered-index", "micro-caps", "none", "hairline-rule"],
      hero: ["full-bleed", "collage", "asymmetric", "boxed-frame"],
      sectionRhythm: ["punctuated-by-fullbleed", "editorial-flow", "uniform", "sparse"],
      featureLayout: ["grid-collage", "stagger", "editorial-list"],
      divider: ["whitespace", "none", "overlap"],
    },
  },
  {
    id: "type-forward",
    label: "Type-forward",
    description: "The type is the design. Oversized display, minimal imagery, layout driven by words.",
    axisAffinity: { convention: "bold", energy: "lively", structure: "loose", era: "current" },
    fitTags: ["agency", "media", "fashion", "portfolio", "music", "events", "design-studio"],
    directives: {
      grid: "Composition built around huge type; images are secondary or absent.",
      type: "A distinctive display face at commanding scale; dramatic size contrast with body.",
      sectionRhythm: "Loose and typographic; headlines set the pace, not cards.",
      heroBias: "Type-only, filling the viewport with a single powerful statement.",
      motifVocabulary: "Oversized headings, kinetic-feeling type, minimal color, letterforms as graphic elements.",
      density: "medium",
      dos: ["Make the words the hero", "Push type scale further than feels safe"],
      donts: ["Don't fall back on a stock image hero", "No timid type sizes"],
    },
    motifEligibility: {
      eyebrow: ["oversized-index", "kicker-line", "none", "micro-caps", "vertical-label"],
      hero: ["type-only", "asymmetric", "split"],
      sectionRhythm: ["editorial-flow", "alternating", "escalating-density"],
      featureLayout: ["editorial-list", "rows", "stagger"],
      divider: ["whitespace", "rule", "overlap"],
    },
  },
  {
    id: "neo-retro",
    label: "Neo-retro",
    description: "A past era revived with intent: chunky forms, warm nostalgic palettes, period motifs, done knowingly.",
    axisAffinity: { convention: "bold", energy: "lively", structure: "balanced", era: "classic" },
    fitTags: ["consumer", "food", "gaming", "music", "dtc"],
    directives: {
      grid: "Period-appropriate composition (70s poster, 90s web, mid-century print) applied deliberately.",
      type: "A characterful retro or revival typeface; period-true color and texture.",
      sectionRhythm: "Lively and varied; period motifs recur as punctuation.",
      heroBias: "Full-bleed poster-like hero or collage with period styling.",
      motifVocabulary: "Grain, halftones, chunky borders, retro badges, warm saturated palette.",
      density: "medium-to-high",
      dos: ["Commit to one era, not a mash of several", "Use period color and texture honestly"],
      donts: ["Don't do generic 'modern' underneath a retro font", "Avoid ironic half-measures"],
    },
    motifEligibility: {
      eyebrow: ["oversized-index", "icon-led", "kicker-line", "numbered-index"],
      hero: ["full-bleed", "collage", "centered"],
      sectionRhythm: ["alternating", "punctuated-by-fullbleed", "escalating-density", "ribbon-bands"],
      featureLayout: ["grid-collage", "cards", "stagger", "carousel"],
      divider: ["shape", "color-block", "overlap"],
    },
  },
  {
    id: "monospace-terminal",
    label: "Monospace / Terminal",
    description: "The developer aesthetic. Mono type, code motifs, spare color, grid discipline, quiet confidence.",
    axisAffinity: { convention: "bold", energy: "measured", structure: "ordered", era: "current" },
    fitTags: ["dev-tools", "infra", "security", "crypto", "ai", "api", "technical"],
    directives: {
      grid: "Tight, exact grid; ASCII-like precision; alignment to a monospace measure.",
      type: "Monospace for accents and labels (sometimes throughout); minimal, high-legibility.",
      sectionRhythm: "Uniform and systematic; content reads like well-formatted output.",
      heroBias: "Type-led or split; a precise statement, maybe a code or terminal motif.",
      motifVocabulary: "Mono labels, hairline borders, terminal/code blocks, restrained accent (often single-hue), dark mode friendly.",
      density: "low-to-medium",
      dos: ["Feel precise and technical", "Use mono type as a signature"],
      donts: ["No soft rounded friendliness", "No stock marketing photography"],
    },
    motifEligibility: {
      eyebrow: ["numbered-index", "hairline-rule", "micro-caps", "none", "tab-chip"],
      hero: ["type-only", "split", "asymmetric"],
      sectionRhythm: ["uniform", "escalating-density"],
      featureLayout: ["rows", "bento", "grid-collage", "table"],
      divider: ["rule", "none", "whitespace"],
    },
  },
  {
    id: "brutalist",
    label: "Brutalist",
    description: "Raw and honest. Exposed structure, harsh contrast, system fonts, deliberate anti-polish.",
    axisAffinity: { convention: "experimental", energy: "lively", structure: "loose", era: "current" },
    fitTags: ["agency", "art", "music", "crypto", "dev-tools", "fashion", "events"],
    directives: {
      grid: "Visible, sometimes broken grid; raw borders; elements butt against each other.",
      type: "System or utilitarian type, big and blunt; unapologetic size contrast.",
      sectionRhythm: "Jarring on purpose; density and scale shift hard between sections.",
      heroBias: "Full-bleed type or asymmetric block; stark, high-contrast, no gloss.",
      motifVocabulary: "Hard borders, raw links, undesigned-looking forms, high contrast, minimal or clashing color.",
      density: "medium-to-high",
      dos: ["Embrace the raw and unpolished", "Let structure show"],
      donts: ["No soft shadows or gradients", "Nothing that reads as 'safe corporate'"],
    },
    motifEligibility: {
      eyebrow: ["oversized-index", "numbered-index", "none", "hairline-rule", "vertical-label"],
      hero: ["type-only", "asymmetric", "full-bleed", "split-diagonal"],
      sectionRhythm: ["escalating-density", "punctuated-by-fullbleed", "alternating"],
      featureLayout: ["rows", "grid-collage", "editorial-list"],
      divider: ["rule", "color-block", "overlap", "angled-cut"],
    },
  },
  {
    id: "organic-handbuilt",
    label: "Organic / Hand-built",
    description: "Warm and imperfect. Asymmetry, hand-drawn accents, natural shapes, nothing rigid.",
    axisAffinity: { convention: "bold", energy: "lively", structure: "organic", era: "current" },
    fitTags: ["wellness", "craft", "food", "kids", "nonprofit", "beauty", "community"],
    directives: {
      grid: "Freeform; elements overlap and sit off-axis; no rigid columns.",
      type: "Warm, slightly characterful type; hand-lettered or humanist accents.",
      sectionRhythm: "Flowing and irregular; organic shapes carry the eye down.",
      heroBias: "Collage or asymmetric with hand-drawn or natural elements.",
      motifVocabulary: "Blobs, hand-drawn strokes, textured fills, natural palette, playful overlaps.",
      density: "medium",
      dos: ["Let it feel handmade and warm", "Use asymmetry and overlap freely"],
      donts: ["Nothing rigid or gridlocked", "Avoid cold geometric perfection"],
    },
    motifEligibility: {
      eyebrow: ["icon-led", "kicker-line", "none", "oversized-index"],
      hero: ["collage", "asymmetric", "split"],
      sectionRhythm: ["editorial-flow", "alternating", "escalating-density"],
      featureLayout: ["stagger", "grid-collage", "cards"],
      divider: ["shape", "overlap", "color-block"],
    },
  },
  {
    id: "playful-toybox",
    label: "Playful / Toybox",
    description: "Bright and bouncy. Rounded forms, big friendly shapes, strong color, motion-forward.",
    axisAffinity: { convention: "bold", energy: "maximal", structure: "loose", era: "current" },
    fitTags: ["consumer", "kids", "food", "gaming", "dtc", "edtech", "fintech-consumer"],
    directives: {
      grid: "Loose, bouncy composition; playful offsets; big rounded shapes anchor sections.",
      type: "Rounded or bold friendly type; big, cheerful scale.",
      sectionRhythm: "High-energy; color blocks and shapes punctuate each section.",
      heroBias: "Centered or collage with big shapes, strong color, an animated feel.",
      motifVocabulary: "Rounded corners, bold shapes, bright multi-color, stickers/badges, gentle motion cues.",
      density: "medium-to-high",
      dos: ["Be bright, friendly, energetic", "Use bold color confidently"],
      donts: ["Nothing austere", "Don't mute the palette into corporate safety"],
    },
    motifEligibility: {
      eyebrow: ["icon-led", "kicker-line", "oversized-index", "none"],
      hero: ["centered", "collage", "split"],
      sectionRhythm: ["alternating", "escalating-density", "punctuated-by-fullbleed", "ribbon-bands"],
      featureLayout: ["cards", "bento", "stagger", "carousel"],
      divider: ["shape", "color-block", "overlap", "gradient-fade"],
    },
  },
  {
    id: "maximalist",
    label: "Maximalist",
    description: "More is more. Dense layering, many type sizes, ornament, collage, controlled chaos.",
    axisAffinity: { convention: "experimental", energy: "maximal", structure: "organic", era: "current" },
    fitTags: ["fashion", "events", "entertainment", "art", "music", "agency", "culture"],
    directives: {
      grid: "Layered and overlapping; multiple focal points; intentional density.",
      type: "Many sizes and weights, mixed families, type as texture.",
      sectionRhythm: "Relentless energy; each section stacks new layers and focal points.",
      heroBias: "Collage or full-bleed packed with layered elements.",
      motifVocabulary: "Overlaps, stickers, mixed media, saturated multi-color, ornament everywhere.",
      density: "high",
      dos: ["Layer boldly", "Fill space with intent, not emptiness"],
      donts: ["Don't retreat to minimal safety", "Avoid a single tidy grid"],
    },
    motifEligibility: {
      eyebrow: ["oversized-index", "icon-led", "kicker-line", "numbered-index"],
      hero: ["collage", "full-bleed", "asymmetric"],
      sectionRhythm: ["escalating-density", "punctuated-by-fullbleed", "editorial-flow"],
      featureLayout: ["grid-collage", "stagger", "bento"],
      divider: ["overlap", "color-block", "shape"],
    },
  },
  {
    id: "techno-futurist",
    label: "Techno-futurist",
    description: "Forward-looking and digital. Dark surfaces, glow and gradient, sharp geometry, a sci-fi edge.",
    axisAffinity: { convention: "experimental", energy: "maximal", structure: "ordered", era: "avant-garde" },
    fitTags: ["ai", "crypto", "gaming", "infra", "deep-tech", "hardware", "space"],
    directives: {
      grid: "Precise geometric grid; sharp edges; a dark canvas with luminous accents.",
      type: "Sharp, technical sans, sometimes wide or condensed; crisp hierarchy.",
      sectionRhythm: "Escalating; glow, gradient, and motion intensify down the page.",
      heroBias: "Full-bleed dark hero with luminous type, 3D or gradient focal element.",
      motifVocabulary: "Dark mode, neon or gradient accents, glow, grid lines, 3D/graphic renders, sharp geometry.",
      density: "medium-to-high",
      dos: ["Feel advanced and premium-technical", "Use dark surfaces and luminous accents"],
      donts: ["No warm hand-made softness", "Avoid stock daylight photography"],
    },
    motifEligibility: {
      eyebrow: ["hairline-rule", "numbered-index", "micro-caps", "kicker-line"],
      hero: ["full-bleed", "split", "asymmetric", "split-diagonal"],
      sectionRhythm: ["escalating-density", "punctuated-by-fullbleed", "uniform"],
      featureLayout: ["bento", "grid-collage", "cards", "table"],
      divider: ["color-block", "rule", "overlap", "gradient-fade", "angled-cut"],
    },
  },

  // ── Art / design MOVEMENTS. Aesthetic-driven, not vertical-driven: any vertical can
  //    wear them. `autoWeight` < 1 keeps them a LIGHT presence in random auto-variety; a
  //    fit match (the movement named in the brief) or a direct pick bypasses that and
  //    surfaces them fully. Each movement name is a fitTag so naming it lands it. ──
  {
    id: "bauhaus",
    label: "Bauhaus",
    description: "Form follows function. Primary geometry, the modular grid, no ornament for its own sake.",
    axisAffinity: { convention: "bold", energy: "measured", structure: "ordered", era: "timeless" },
    fitTags: ["bauhaus", "modernist", "art", "design-studio", "architecture", "editorial", "b2b"],
    autoWeight: 0.24,
    directives: {
      grid: "Strict modular grid; primary geometric forms (circle, triangle, square) used as structural, not decorative, elements.",
      type: "Geometric sans (Futura-like), often lowercase, tight and functional.",
      sectionRhythm: "Even and systematic; the geometry and grid carry the rhythm.",
      heroBias: "Type set against primary geometric shapes in asymmetric balance.",
      motifVocabulary: "Primary red / blue / yellow on black and white, hard geometry, thick rules, exposed structure.",
      density: "medium",
      dos: ["Use primary color and basic geometry with intent", "Let form follow function"],
      donts: ["No ornament for its own sake", "No gradients or soft shadows"],
    },
    motifEligibility: {
      eyebrow: ["numbered-index", "hairline-rule", "none"],
      hero: ["asymmetric", "type-only", "split"],
      sectionRhythm: ["uniform", "alternating"],
      featureLayout: ["grid-collage", "bento", "rows"],
      divider: ["rule", "color-block", "none"],
    },
  },
  {
    id: "mid-century-modern",
    label: "Mid-Century Modern",
    description: "Atomic-age optimism. Warm muted palette, organic curves meeting clean lines.",
    axisAffinity: { convention: "familiar", energy: "measured", structure: "balanced", era: "classic" },
    fitTags: ["mid-century", "furniture", "hospitality", "lifestyle", "architecture", "consumer", "interior"],
    autoWeight: 0.28,
    directives: {
      grid: "Balanced and airy; organic curves alongside clean horizontal lines.",
      type: "Warm humanist or friendly geometric sans; clean but never cold.",
      sectionRhythm: "Calm and even; atomic-age motifs punctuate.",
      heroBias: "Split or full-bleed with a warm muted palette and a mid-century illustration or photo.",
      motifVocabulary: "Mustard / teal / burnt-orange / walnut palette, starbursts, boomerangs, atomic shapes, warm wood texture.",
      density: "medium",
      dos: ["Use a warm muted retro palette", "Blend organic curves with clean geometry"],
      donts: ["No cold minimalism", "No neon or high-gloss"],
    },
    motifEligibility: {
      eyebrow: ["micro-caps", "kicker-line", "none"],
      hero: ["split", "full-bleed", "centered", "boxed-frame"],
      sectionRhythm: ["uniform", "alternating"],
      featureLayout: ["cards", "rows", "stagger"],
      divider: ["shape", "whitespace", "color-block"],
    },
  },
  {
    id: "art-deco",
    label: "Art Deco",
    description: "Machine-age glamour. Symmetry, vertical emphasis, gold on dark, geometric ornament.",
    axisAffinity: { convention: "bold", energy: "lively", structure: "ordered", era: "classic" },
    fitTags: ["art-deco", "deco", "luxury", "hospitality", "jewelry", "events", "beauty", "fashion"],
    autoWeight: 0.24,
    directives: {
      grid: "Symmetrical with strong vertical emphasis; ornamental geometric framing.",
      type: "High-contrast geometric display, elegant, often uppercase with wide tracking.",
      sectionRhythm: "Grand and symmetric; framed, formal sections.",
      heroBias: "Centered, symmetric hero: gold-on-dark with geometric ornament.",
      motifVocabulary: "Gold and metallics on black or deep jewel tones, sunbursts, chevrons, stepped forms, thin precise lines.",
      density: "medium-to-high",
      dos: ["Embrace symmetry and geometric ornament", "Use gold / metallic accents on dark"],
      donts: ["No casual asymmetry", "Nothing flat or utilitarian"],
    },
    motifEligibility: {
      eyebrow: ["oversized-index", "micro-caps", "hairline-rule"],
      hero: ["centered", "editorial-cover", "full-bleed", "boxed-frame"],
      sectionRhythm: ["uniform", "punctuated-by-fullbleed"],
      featureLayout: ["grid-collage", "cards", "rows"],
      divider: ["rule", "color-block", "shape"],
    },
  },
  {
    id: "memphis",
    label: "Memphis",
    description: "Gleeful 80s postmodernism. Clashing brights, squiggles, and geometry that refuses to behave.",
    axisAffinity: { convention: "experimental", energy: "maximal", structure: "loose", era: "classic" },
    fitTags: ["memphis", "postmodern", "playful", "events", "gaming", "consumer", "art", "music"],
    autoWeight: 0.2,
    directives: {
      grid: "Loose and playful; clashing shapes float, tilt, and overlap.",
      type: "Bold and mixed; unexpected, irreverent pairings.",
      sectionRhythm: "High energy; confetti geometry scatters between sections.",
      heroBias: "Collage of clashing bright shapes and squiggles.",
      motifVocabulary: "Clashing brights (hot pink / teal / yellow), squiggles, zigzags, confetti dots, terrazzo, 80s energy.",
      density: "high",
      dos: ["Clash colors and shapes on purpose", "Be irreverent"],
      donts: ["Nothing tasteful-minimal", "Do not tidy it into a neat grid"],
    },
    motifEligibility: {
      eyebrow: ["oversized-index", "icon-led", "kicker-line"],
      hero: ["collage", "asymmetric", "centered"],
      sectionRhythm: ["escalating-density", "punctuated-by-fullbleed", "ribbon-bands"],
      featureLayout: ["grid-collage", "bento", "stagger"],
      divider: ["shape", "color-block", "overlap", "angled-cut"],
    },
  },
  {
    id: "constructivist",
    label: "Constructivist",
    description: "Revolutionary energy. Bold diagonals, red and black, photomontage, propaganda-poster force.",
    axisAffinity: { convention: "experimental", energy: "lively", structure: "loose", era: "classic" },
    fitTags: ["constructivist", "agency", "art", "music", "editorial", "events", "culture"],
    autoWeight: 0.2,
    directives: {
      grid: "Dynamic diagonals; asymmetric, angular compositions.",
      type: "Heavy grotesque, often uppercase, set on strong angles.",
      sectionRhythm: "Propulsive; diagonal energy drives down the page.",
      heroBias: "Bold diagonal composition in red / black with photomontage.",
      motifVocabulary: "Red, black, and cream, hard diagonals, angular blocks, photomontage, poster energy.",
      density: "medium-to-high",
      dos: ["Use diagonals and red / black boldly", "Compose on the angle"],
      donts: ["No centered symmetry", "Nothing soft or pastel"],
    },
    motifEligibility: {
      eyebrow: ["oversized-index", "numbered-index", "none"],
      hero: ["asymmetric", "collage", "type-only", "split-diagonal"],
      sectionRhythm: ["escalating-density", "alternating"],
      featureLayout: ["grid-collage", "rows", "editorial-list"],
      divider: ["rule", "color-block", "overlap", "angled-cut"],
    },
  },
  {
    id: "de-stijl",
    label: "De Stijl",
    description: "Pure abstraction. Primary-colored rectangles divided by heavy black lines, Mondrian's grid.",
    axisAffinity: { convention: "experimental", energy: "measured", structure: "ordered", era: "timeless" },
    fitTags: ["de-stijl", "mondrian", "art", "design-studio", "architecture", "editorial", "b2b"],
    autoWeight: 0.2,
    directives: {
      grid: "Rectangular blocks divided by heavy black lines; the grid IS the composition.",
      type: "Clean geometric sans placed within the blocked grid.",
      sectionRhythm: "Modular colored blocks; flat and abstract.",
      heroBias: "Mondrian-style blocked hero: primaries and black dividing lines.",
      motifVocabulary: "Primary red / blue / yellow and white, thick black lines, pure rectangles, no curves.",
      density: "medium",
      dos: ["Compose in primary-colored rectangles and black lines", "Keep it flat and abstract"],
      donts: ["No curves, no imagery-heavy layouts", "No gradients"],
    },
    motifEligibility: {
      eyebrow: ["none", "hairline-rule", "numbered-index"],
      hero: ["type-only", "asymmetric", "split"],
      sectionRhythm: ["uniform", "alternating"],
      featureLayout: ["bento", "grid-collage", "rows"],
      divider: ["rule", "color-block", "none"],
    },
  },
  {
    id: "art-nouveau",
    label: "Art Nouveau",
    description: "Organic elegance. Whiplash curves, botanical linework, and flowing ornament.",
    axisAffinity: { convention: "bold", energy: "measured", structure: "organic", era: "classic" },
    fitTags: ["art-nouveau", "nouveau", "beauty", "luxury", "hospitality", "culture", "fashion", "wellness"],
    autoWeight: 0.2,
    directives: {
      grid: "Flowing, organic composition; botanical framing around the content.",
      type: "Ornate flowing display with organic curves.",
      sectionRhythm: "Graceful, curvilinear transitions.",
      heroBias: "Full-bleed with flowing botanical linework and elegant type.",
      motifVocabulary: "Whiplash curves, botanical motifs, muted jewel and earth tones, ornamental borders, flowing linework.",
      density: "medium-to-high",
      dos: ["Use flowing organic linework and botanicals", "Let curves lead"],
      donts: ["No hard grids", "Nothing stark or brutalist"],
    },
    motifEligibility: {
      eyebrow: ["kicker-line", "icon-led", "none"],
      hero: ["full-bleed", "collage", "editorial-cover"],
      sectionRhythm: ["editorial-flow", "punctuated-by-fullbleed"],
      featureLayout: ["editorial-list", "stagger", "grid-collage"],
      divider: ["shape", "overlap", "whitespace"],
    },
  },
  {
    id: "psychedelic",
    label: "Psychedelic",
    description: "60s immersion. Warping type, kaleidoscopic color, hand-drawn poster energy.",
    axisAffinity: { convention: "experimental", energy: "maximal", structure: "organic", era: "classic" },
    fitTags: ["psychedelic", "music", "festival", "events", "art", "culture", "entertainment"],
    autoWeight: 0.16,
    directives: {
      grid: "Freeform and warping; type and shape melt together.",
      type: "Ornate warping display with a hand-drawn feel.",
      sectionRhythm: "Swirling and immersive; color washes flow between sections.",
      heroBias: "Full-bleed swirling color with warped lettering.",
      motifVocabulary: "High-saturation clashing color, swirls, warped type, kaleidoscopic symmetry, 60s poster energy.",
      density: "high",
      dos: ["Warp type and saturate color", "Be immersive and ornate"],
      donts: ["Nothing minimal or corporate", "No tidy grid"],
    },
    motifEligibility: {
      eyebrow: ["oversized-index", "icon-led", "none"],
      hero: ["full-bleed", "collage", "type-only"],
      sectionRhythm: ["punctuated-by-fullbleed", "escalating-density"],
      featureLayout: ["grid-collage", "stagger", "editorial-list"],
      divider: ["shape", "overlap", "color-block"],
    },
  },
  {
    id: "y2k-futurist",
    label: "Y2K Futurist",
    description: "Turn-of-the-millennium digital. Chrome, iridescent gradients, glossy retro-futurism.",
    axisAffinity: { convention: "experimental", energy: "maximal", structure: "loose", era: "current" },
    fitTags: ["y2k", "vaporwave", "gaming", "music", "fashion", "crypto", "entertainment", "dtc"],
    autoWeight: 0.2,
    directives: {
      grid: "Loose and layered; chrome and glossy UI fragments.",
      type: "Techno, pixel, or glossy chrome display.",
      sectionRhythm: "Restless; gradients and glints between sections.",
      heroBias: "Full-bleed chrome or gradient with glossy 3D or pixel motifs.",
      motifVocabulary: "Chrome, iridescent gradients, glossy bubbles, pixel / lo-fi, cyber blues and purples, early-web nostalgia.",
      density: "high",
      dos: ["Use chrome and iridescent gradients", "Lean into early-2000s digital"],
      donts: ["Nothing flat-minimal", "No muted earth tones"],
    },
    motifEligibility: {
      eyebrow: ["icon-led", "oversized-index", "none"],
      hero: ["full-bleed", "collage", "asymmetric", "split-diagonal"],
      sectionRhythm: ["escalating-density", "punctuated-by-fullbleed"],
      featureLayout: ["bento", "grid-collage", "cards", "carousel"],
      divider: ["color-block", "overlap", "shape", "gradient-fade"],
    },
  },
];

module.exports = { AXES, AXIS_RUBRIC, MOTIFS, MOTIF_GLOSS, MOTIF_AFFINITY, LENSES };
